### ISSUE TITLE
3 hata

### ISSUE THREAD

**Issue by ugurrk35** [OrionVx/Nop.Plugin.Payments.Iyzico#1]
payment error hatası aldım  daha sonra iyzico paneli açtım 
iyzico validasyon hataları bölümünden
|Geçersiz imza | 1000
 binNumber 6 karakter olmalıdır | 5007
binNumber sayısal olmalıdır | 50000
 çözümü nedir acaba

**Comment by fetullahyldz** [comment]
Merhaba Aynı sorun bendede var ancak binNumber 6 karakter olmalıdır | 5007 çözdüm yine hata veriyor geçersiz istek 1000 hatası 

BinNumber = paymentCard.CardNumber.ToString().Substring(0, 6),  bu şekilde yaparsanız çalışır. instalment kısmından

**Comment by kucukemre** [comment]
Merhaba,
Hatalar çözülüp, plugin nopCommerce v4.30 versiyonuna geçirilmiştir.
